language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tshark
script:
  - pip install -r requirements.txt
  - cd src/
  - python setup.py install
  - cd ../tests
  - py.test
  
